import {
  slugify
} from "../../lib/guildSiteStore.js";
import {
  getActiveInviteToken,
  isActiveInviteLink
} from "./routeUtils.js";

export function buildGuildOpsControllerProps({
  absenceController,
  activeGuilds,
  activeView,
  administrationAccess,
  approveMembershipRequest,
  authSession,
  bankController,
  banGuildMember,
  blockMembershipRequest,
  changeActiveGuild,
  createGuild,
  creatingGuild,
  currentUser,
  diplomacyController,
  disableGuildOpsModule,
  effectiveEnabledModuleIds,
  enableGuildOpsModule,
  enabledModuleIds,
  eventsController,
  forumController,
  guildCreateError,
  guildOpsState,
  inviteRouteSlug,
  lastPublishedSite,
  memberBlocks,
  memberModerationError,
  membershipRequests,
  messagesController,
  notificationsController,
  mobileNavItems,
  moduleUpdateError,
  moderatingMemberId,
  navItems,
  navigateToPath,
  navigateToView,
  openPublicSite,
  publicDiplomacy,
  publicForum,
  publicRouteSegment,
  publicRouteSlug,
  publicSiteUrl,
  publishGuildSite,
  publishingSite,
  purchaseTemplateDesign,
  purchasedDesignIds,
  refuseMembershipRequest,
  requestGuildMembership,
  roleEdits,
  rotateInviteLink,
  rotatingInviteLink,
  routePath,
  selectedGuild,
  setRoleEdits,
  setSiteDraft,
  setSitePublished,
  siteDraft,
  sitePublishError,
  sitePublished,
  sosController,
  toggleAdministrationMember,
  toggleAdministrationModule,
  toggleAllAdministrationModules,
  unblockGuildMember,
  useTemplateDesign
}) {
  const notificationProps = {
    notifications: notificationsController.notifications,
    notificationError: notificationsController.notificationError,
    pushState: notificationsController.pushState,
    unreadNotifications: notificationsController.unreadNotificationCount,
    onDisablePush: notificationsController.disablePushNotifications,
    onEnablePush: notificationsController.enablePushNotifications,
    onMarkAllRead: notificationsController.markAllNotificationsRead,
    onOpenNotification: async (notification) => {
      if (!notification?.id) return;

      await notificationsController.markNotificationRead(notification.id);
      const url = typeof notification.data?.url === "string" ? notification.data.url : "";
      if (url) {
        navigateToPath(url);
      }
    },
  };

  return {
    activeGuilds,
    activeView,
    authSession,
    guildOpsState,
    inviteRouteSlug,
    publicRouteSlug,
    routePath,
    onNavigatePath: navigateToPath,
    landingProps: {
      onOpenApp: () => navigateToPath("/app"),
      onOpenGallery: () => navigateToPath("/guildes"),
      onOpenLogin: () => navigateToPath("/auth/login"),
      onOpenRegister: () => navigateToPath("/auth/register"),
    },
    publicRouteProps: {
      acknowledgeSos: sosController.acknowledgeSos,
      createEvent: eventsController.createEvent,
      creatingEvent: eventsController.creatingEvent,
      currentUser,
      enabledModuleIds: effectiveEnabledModuleIds,
      eventCreateError: eventsController.eventCreateError,
      events: eventsController.activeEvents,
      fallbackSite: lastPublishedSite,
      memberGuilds: activeGuilds,
      members: eventsController.members,
      moduleManagementProps: {
        bank: {
          addBankMovement: bankController.addBankMovement,
          bankCommand: bankController.bankCommand,
          bankError: bankController.bankError,
          bankMovements: bankController.bankMovementsLog,
          bankRequests: bankController.bankRequests,
          bankStock: bankController.bankStock,
          createBankRequest: bankController.createBankRequest,
          saveBankResource: bankController.saveBankResource,
          setBankCommand: bankController.setBankCommand,
          updateBankRequestStatus: bankController.updateBankRequestStatus,
        },
        diplomacy: {
          diplomacyAudit: diplomacyController.diplomacyAudit,
          diplomacyCoordinates: diplomacyController.diplomacyCoordinates,
          diplomacyError: diplomacyController.diplomacyError,
          diplomacyNapAgreements: diplomacyController.diplomacyNapAgreements,
          diplomacyRelations: diplomacyController.diplomacyRelations,
          saveDiplomacyCoordinate: diplomacyController.saveDiplomacyCoordinate,
          saveDiplomacyRelation: diplomacyController.saveDiplomacyRelation,
          saveNapAgreement: diplomacyController.saveNapAgreement,
        },
        forum: {
          activeForumCategoryId: forumController.activeForumCategoryId,
          activeForumThread: forumController.activeForumThread,
          forumCanManage: forumController.forumCanManage,
          forumCategories: forumController.forumCategories,
          forumCategoryDraft: forumController.forumCategoryDraft,
          forumCounters: forumController.forumCounters,
          forumEditingPostId: forumController.forumEditingPostId,
          forumError: forumController.forumError,
          forumLoading: forumController.forumLoading,
          forumMutes: forumController.forumMutes,
          forumPostPagination: forumController.forumPostPagination,
          forumPosts: forumController.forumPosts,
          forumReplyDraft: forumController.forumReplyDraft,
          forumRoles: forumController.forumRoles,
          forumThreadDraft: forumController.forumThreadDraft,
          forumThreadPagination: forumController.forumThreadPagination,
          forumThreads: forumController.forumThreadsState,
          onCreateForumThread: forumController.createForumThread,
          onDeleteForumCategory: forumController.deleteForumCategory,
          onDeleteForumPost: forumController.deleteForumPost,
          onDeleteForumThread: forumController.deleteForumThread,
          onEditForumPost: forumController.beginForumPostEdit,
          onMuteForumMember: forumController.muteForumMember,
          onSaveForumCategory: forumController.saveForumCategory,
          onSaveForumCategoryPermissions: forumController.saveForumCategoryPermissions,
          onSelectForumCategory: forumController.selectForumCategory,
          onSelectForumThread: forumController.selectForumThread,
          onSendForumReply: forumController.sendForumReply,
          onUnmuteForumMember: forumController.unmuteForumMember,
          onUpdateForumThreadFlags: forumController.updateForumThreadFlags,
          setForumCategoryDraft: forumController.setForumCategoryDraft,
          setForumReplyDraft: forumController.setForumReplyDraft,
          setForumThreadDraft: forumController.setForumThreadDraft,
        },
        membership: {
          memberModerationError,
          membershipRequests,
          moderatingMemberId,
          onApproveMembershipRequest: approveMembershipRequest,
          onBlockMembershipRequest: blockMembershipRequest,
          onRefuseMembershipRequest: refuseMembershipRequest,
          onRotateInviteLink: rotateInviteLink,
          rotatingInviteLink,
          selectedGuild,
        },
      },
      publicDiplomacy,
      publicForum,
      onNavigatePublicRoute: navigateToPath,
      onBackToBuilder: () => navigateToPath("/app"),
      routeSegment: publicRouteSegment,
      sendSos: sosController.sendSos,
      setSosForm: sosController.setSosForm,
      slug: publicRouteSlug,
      sosAlerts: sosController.sosAlerts,
      sosError: sosController.sosError,
      sosForm: sosController.sosForm,
      sosRealtimeStatus: sosController.sosRealtimeStatus,
      unreadMessages: messagesController.unreadMessageCount,
      warSummary: eventsController.warSummary,
    },
    joinRouteProps: {
      authSession,
      inviteSlug: inviteRouteSlug,
      isInviteLink: isActiveInviteLink(),
      inviteToken: getActiveInviteToken(),
      memberBlocks,
      onJoined: async () => {
        await authSession.reload?.();
        await guildOpsState.reload?.();
      },
      onOpenApp: () => navigateToPath("/app"),
      onOpenPublicSite: (slug = inviteRouteSlug) => navigateToPath(`/g/${slugify(slug)}`),
      onRequestJoin: requestGuildMembership,
    },
    onboardingProps: {
      creating: creatingGuild,
      currentUser,
      error: guildCreateError,
      onCreateGuild: createGuild,
      organizations: authSession.organizations,
    },
    sidebarProps: {
      activeView,
      guilds: activeGuilds,
      navItems,
      onGuildChange: changeActiveGuild,
      onNavigate: navigateToView,
      selectedGuild,
      unreadMessages: messagesController.unreadMessageCount,
    },
    mobileHeaderProps: {
      activeView,
      navItems,
      notificationProps,
      onNavigate: navigateToView,
      onOpenMessages: () => navigateToView("messages"),
      selectedGuild,
      unreadMessages: messagesController.unreadMessageCount,
    },
    topBarProps: {
      currentUser,
      guilds: activeGuilds,
      onCreateSite: publishGuildSite,
      selectedGuild,
      sitePublished,
      publishingSite,
      publicSiteUrl,
      sitePublishError,
      onGuildChange: changeActiveGuild,
      onOpenMessages: () => navigateToView("messages"),
      onOpenMemberSpace: () => navigateToView("member"),
      onOpenPublicSite: openPublicSite,
      onLogout: authSession.isApiEnabled ? authSession.logout : null,
      notificationProps,
      unreadMessages: messagesController.unreadMessageCount,
    },
    viewRouterProps: {
      activeView,
      administrationAccess,
      absenceDraft: absenceController.absenceDraft,
      absenceError: absenceController.absenceError,
      absenceSummary: absenceController.absenceSummary,
      absences: absenceController.absences,
      authSession,
      currentUser,
      enabledModuleIds,
      moduleUpdateError,
      purchasedDesignIds,
      onDeleteAbsence: absenceController.deleteAbsence,
      onDisableModule: disableGuildOpsModule,
      onEnableModule: enableGuildOpsModule,
      onPurchaseTemplate: purchaseTemplateDesign,
      onUseTemplate: useTemplateDesign,
      onToggleAdministrationMember: toggleAdministrationMember,
      onToggleAdministrationModule: toggleAdministrationModule,
      onToggleAllAdministrationModules: toggleAllAdministrationModules,
      selectedGuild,
      members: eventsController.members,
      memberBlocks,
      memberModerationError,
      moderatingMemberId,
      membershipRequests,
      onApproveMembershipRequest: approveMembershipRequest,
      onBanGuildMember: banGuildMember,
      onBlockMembershipRequest: blockMembershipRequest,
      onRefuseMembershipRequest: refuseMembershipRequest,
      onRotateInviteLink: rotateInviteLink,
      onSubmitAbsence: absenceController.submitAbsence,
      onUnblockGuildMember: unblockGuildMember,
      rotatingInviteLink,
      selfStatus: eventsController.selfStatus,
      setSelfStatus: eventsController.setSelfStatus,
      events: eventsController.activeEvents,
      createEvent: eventsController.createEvent,
      creatingEvent: eventsController.creatingEvent,
      eventCreateError: eventsController.eventCreateError,
      checkIn: eventsController.checkIn,
      checkinError: eventsController.checkinError,
      warSummary: eventsController.warSummary,
      updateMemberStatus: eventsController.updateMemberStatus,
      translateOn: messagesController.translateOn,
      setTranslateOn: messagesController.setTranslateOn,
      targetLanguage: messagesController.targetLanguage,
      setTargetLanguage: messagesController.changeTargetLanguage,
      chatMessages: messagesController.chatMessages,
      chatDraft: messagesController.chatDraft,
      chatNotice: messagesController.chatNotice,
      chatCooldownSeconds: messagesController.chatCooldownRemaining,
      setChatDraft: messagesController.setChatDraft,
      sendChat: messagesController.sendChat,
      conversations: messagesController.conversations,
      activeConversation: messagesController.activeConversation,
      onSelectConversation: messagesController.selectConversation,
      threadMessages: messagesController.threadMessages,
      messageAttachment: messagesController.messageAttachment,
      messageDraft: messagesController.messageDraft,
      onAttachMessageImage: messagesController.attachMessageImage,
      onClearMessageAttachment: messagesController.clearMessageAttachment,
      setMessageDraft: messagesController.setMessageDraft,
      sendGuildThreadMessage: messagesController.sendGuildThreadMessage,
      messageReplyTarget: messagesController.messageReplyTarget,
      onCancelMessageReply: messagesController.cancelThreadMessageReply,
      loadOlderThreadMessages: messagesController.loadOlderThreadMessages,
      messageNextCursor: messagesController.messageNextCursor,
      messageRecipients: messagesController.messageRecipients,
      onAddConversationMember: messagesController.addMessageParticipant,
      onDeleteConversation: messagesController.deleteConversation,
      onInviteByEmail: messagesController.inviteMessageRecipientByEmail,
      onLeaveGroupConversation: messagesController.leaveGroupConversation,
      onReplyToThreadMessage: messagesController.replyToThreadMessage,
      onRemoveConversationMember: messagesController.removeMessageParticipant,
      onStartGroupConversation: messagesController.startGroupConversation,
      onStartPrivateConversation: messagesController.startPrivateConversation,
      onToggleThreadMessageLike: messagesController.toggleThreadMessageLike,
      unreadMessageCount: messagesController.unreadMessageCount,
      messageRealtimeStatus: messagesController.messageRealtimeStatus,
      messageError: messagesController.messageError,
      forumCategories: forumController.forumCategories,
      forumRoles: forumController.forumRoles,
      forumCounters: forumController.forumCounters,
      forumCanManage: forumController.forumCanManage,
      activeForumCategoryId: forumController.activeForumCategoryId,
      onSelectForumCategory: forumController.selectForumCategory,
      forumThreads: forumController.forumThreadsState,
      activeForumThread: forumController.activeForumThread,
      onSelectForumThread: forumController.selectForumThread,
      forumPosts: forumController.forumPosts,
      forumThreadPagination: forumController.forumThreadPagination,
      forumPostPagination: forumController.forumPostPagination,
      forumThreadDraft: forumController.forumThreadDraft,
      setForumThreadDraft: forumController.setForumThreadDraft,
      forumReplyDraft: forumController.forumReplyDraft,
      setForumReplyDraft: forumController.setForumReplyDraft,
      forumCategoryDraft: forumController.forumCategoryDraft,
      setForumCategoryDraft: forumController.setForumCategoryDraft,
      forumEditingPostId: forumController.forumEditingPostId,
      forumError: forumController.forumError,
      forumLoading: forumController.forumLoading,
      forumMutes: forumController.forumMutes,
      onSaveForumCategory: forumController.saveForumCategory,
      onSaveForumCategoryPermissions: forumController.saveForumCategoryPermissions,
      onCreateForumThread: forumController.createForumThread,
      onDeleteForumCategory: forumController.deleteForumCategory,
      onDeleteForumThread: forumController.deleteForumThread,
      onUpdateForumThreadFlags: forumController.updateForumThreadFlags,
      onSendForumReply: forumController.sendForumReply,
      onEditForumPost: forumController.beginForumPostEdit,
      onDeleteForumPost: forumController.deleteForumPost,
      onMuteForumMember: forumController.muteForumMember,
      onUnmuteForumMember: forumController.unmuteForumMember,
      diplomacyRelations: diplomacyController.diplomacyRelations,
      diplomacyNapAgreements: diplomacyController.diplomacyNapAgreements,
      diplomacyCoordinates: diplomacyController.diplomacyCoordinates,
      diplomacyAudit: diplomacyController.diplomacyAudit,
      diplomacyError: diplomacyController.diplomacyError,
      saveDiplomacyRelation: diplomacyController.saveDiplomacyRelation,
      saveNapAgreement: diplomacyController.saveNapAgreement,
      saveDiplomacyCoordinate: diplomacyController.saveDiplomacyCoordinate,
      sosAlerts: sosController.sosAlerts,
      sosForm: sosController.sosForm,
      sosRealtimeStatus: sosController.sosRealtimeStatus,
      sosError: sosController.sosError,
      setSosForm: sosController.setSosForm,
      sendSos: sosController.sendSos,
      acknowledgeSos: sosController.acknowledgeSos,
      bankRequests: bankController.bankRequests,
      bankError: bankController.bankError,
      approveRequest: bankController.approveRequest,
      createBankRequest: bankController.createBankRequest,
      updateBankRequestStatus: bankController.updateBankRequestStatus,
      bankStock: bankController.bankStock,
      bankMovements: bankController.bankMovementsLog,
      addBankMovement: bankController.addBankMovement,
      saveBankResource: bankController.saveBankResource,
      bankCommand: bankController.bankCommand,
      setBankCommand: bankController.setBankCommand,
      siteDraft,
      setSiteDraft,
      setAbsenceDraft: absenceController.setAbsenceDraft,
      publishGuildSite,
      publishingSite,
      sitePublishError,
      publicSiteUrl,
      onOpenPublicSite: openPublicSite,
      sitePublished,
      setSitePublished,
      guilds: activeGuilds,
      roleEdits,
      setRoleEdits,
      onGuildChange: changeActiveGuild,
      onNavigate: navigateToView,
    },
    mobileBottomNavProps: {
      activeView,
      mobileNav: mobileNavItems,
      onNavigate: navigateToView,
      unreadMessages: messagesController.unreadMessageCount,
    },
  };
}
